### ISSUE TITLE
[1.18.1] Won't let me upgrade my tool belt

### ISSUE THREAD

**Issue by VoxelFloof** [gigaherz/ToolBelt#114]
![2022-03-16_13 46 06](https://user-images.githubusercontent.com/94568504/158665651-c0ff5412-cbd1-473d-9048-3580e9df149c.png)

**Comment by gigaherz** [comment]
If you have Sewing Kit installed you need to use the sewing recipes to upgrade.

**Comment by LtSZECHUAN** [comment]
Hey i have the same issue, and dont have, nor have i ever had the sewing kit mod

**Comment by gigaherz** [comment]
The anvil works fine for me without Sewing Kit. 

![image](https://user-images.githubusercontent.com/685851/162846532-3258c1b2-9656-476a-964d-d6dcdef4a2e3.png)

First, make sure the toolbelt-common.toml config values disableAnvilUpgrading and anvilUpgrading are not interfering.

```toml
	#If set to FALSE, support for sewing recipes will not be enabled regardless of the mod's presence.
	disableAnvilUpgrading = false
	#If AUTO, the crafting and upgrade recipes will use the Sewing mechanics if the Sewing Kit mod is present. Off disables anvil upgrading regardless.
	#Allowed Values: OFF, AUTO, ON
	anvilUpgrading = "AUTO"
```

If the configs are not disabling anvil use, and you play in a modpack, it must be some other mod cancelling the anvil use before Tool belt can set its own recipe. You will have to identify which mod is doing it.
